<?php

namespace Database\Seeders;

//use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PurchaseHistorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('purchaseHistory')->insert([
            [
                'PO' => 1015,
                'Pdate' => '2022-02-10',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing',
                'qty' => 10,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 500.00,
                'user' => 'user',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:51',
            ],
            [
                'PO' => 1016,
                'Pdate' => '2022-02-12',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing',
                'qty' => 10,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 500.00,
                'user' => 'user',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:51',
            ],
            [
                'PO' => 1019,
                'Pdate' => '2022-02-10',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 10,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 500.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:51',
            ],
            [
                'PO' => 10001,
                'Pdate' => '2022-02-15',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing',
                'qty' => 10,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 584.00,
                'user' => 'user',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:52',
            ],
            [
                'PO' => 10002,
                'Pdate' => '2022-08-15',
                'item_list' => 'DPD - 001',
                'material_desc' => 'Testing',
                'qty' => 50,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 584.00,
                'user' => 'user',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:52',
            ],
            [
                'PO' => 10003,
                'Pdate' => '2023-02-15',
                'item_list' => 'DPD - 008',
                'material_desc' => 'Testing',
                'qty' => 50,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 584.00,
                'user' => 'user',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:52',
            ],
            [
                'PO' => 10005,
                'Pdate' => '2024-01-15',
                'item_list' => 'DPD - 008',
                'material_desc' => 'Testing',
                'qty' => 50,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 584.00,
                'user' => 'Chalise',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:52',
            ],
            [
                'PO' => 10006,
                'Pdate' => '2024-01-25',
                'item_list' => 'DPD - 008',
                'material_desc' => 'Testing',
                'qty' => 50,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 584.00,
                'user' => 'Chalise',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:53',
            ],
            [
                'PO' => 10009,
                'Pdate' => '2024-01-26',
                'item_list' => 'DPD - 008',
                'material_desc' => 'Testing',
                'qty' => 50,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 584.00,
                'user' => 'Chalise',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:53',
            ],
            [
                'PO' => 10120,
                'Pdate' => '2022-02-10',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 10,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:53',
            ],
            [
                'PO' => 10121,
                'Pdate' => '2022-02-10',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 10,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:53',
            ],
            [
                'PO' => 10122,
                'Pdate' => '2024-02-10',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 10,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:53',
            ],
            [
                'PO' => 10123,
                'Pdate' => '2024-02-10',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 1,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:54',
            ],
            [
                'PO' => 10124,
                'Pdate' => '2024-02-21',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 1,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:54',
            ],
            [
                'PO' => 10125,
                'Pdate' => '2024-02-21',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 1,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:54',
            ],
            [
                'PO' => 10126,
                'Pdate' => '2024-02-21',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 27,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:54',
            ],
            [
                'PO' => 10127,
                'Pdate' => '2024-02-21',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 27,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:55',
            ],
            [
                'PO' => 10128,
                'Pdate' => '2024-02-21',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 27,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:55',
            ],
            [
                'PO' => 10129,
                'Pdate' => '2024-02-21',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 27,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:55',
            ],
            [
                'PO' => 10130,
                'Pdate' => '2024-02-21',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing-2',
                'qty' => 27,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 59.00,
                'user' => 'Chhabi',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => null,
                'updated_at' => '2024-05-25 15:58:55',
            ],
            [
                'PO' => 2151015,
                'Pdate' => '2024-05-24',
                'item_list' => 'DPD - 007',
                'material_desc' => 'Testing',
                'qty' => 10,
                'u_price' => 1.00,
                'unit' => 'LTR',
                'p_price' => 500.00,
                'user' => 'user',
                'category' => 'Dairy Products',
                'supplier_id' => 2,
                'Rdate' => null,
                'paid_status' => 3,
                'created_at' => '2024-05-24 08:44:17',
                'updated_at' => '2024-05-25 15:58:56',
            ],
        ]);
    }
}
